version: "3.3"
services:
  spark-master:
    build: .
    ports:
      - "9090:8080"
      - "7077:7077"
      - "2222:22"
    volumes:
       - ../../etl/transformation:/opt/app/transformation
       - ../../etl/load:/opt/app/load
       - ../../etl/ingestion:/opt/app/ingestion
       - ../../data:/opt/data

    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      - ggazers_nw
    command: >
             bash -c "/etc/init.d/ssh start && ./start-spark.sh"

  spark-worker-a:
    build: .
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ../../etl/transformation:/opt/app/transformation
       - ../../etl/load:/opt/app/load
       - ../../etl/ingestion:/opt/app/ingestion
       - ../../data:/opt/data

    networks:
      - ggazers_nw
    command: >
             bash -c "/etc/init.d/ssh start && ./start-spark.sh"

  spark-worker-b:
    build: .
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
       - ../../etl/transformation:/opt/app/transformation
       - ../../etl/load:/opt/app/load
       - ../../etl/ingestion:/opt/app/ingestion
       - ../../data:/opt/data
    networks:
      - ggazers_nw
    command: >
             bash -c "/etc/init.d/ssh start && ./start-spark.sh"

networks:
  ggazers_nw:
    driver: bridge
    name: ggazers_nw