services:
  broker:
    image: confluentinc/cp-kafka:7.3.1
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:9095,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9095'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./update_run.sh:/tmp/update_run.sh
    command: "bash -c 'if [ ! -f /tmp/update_run.sh ]; then echo \"ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?\" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'"
    networks:
      - ggazers_nw

  kafka-topic-setup:
    image: confluentinc/cp-kafka:7.3.1
    container_name: kafka-topic-setup
    depends_on:
      - broker
    command: |
      bash -c '
        echo Waiting for Kafka to be ready... &&
        cub kafka-ready -b broker:29092 1 20 &&
        kafka-topics --create --if-not-exists --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --topic ggazers.github.push_events &&
        kafka-topics --create --if-not-exists --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --config cleanup.policy=compact --topic ggazers.github.repos &&
        kafka-topics --create --if-not-exists --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --config cleanup.policy=compact --topic ggazers.github.actors &&
        kafka-topics --create --if-not-exists --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --topic ggazers.github.repo_kpi &&
        kafka-topics --create --if-not-exists --bootstrap-server broker:29092 --partitions 1 --replication-factor 1 --topic ggazers.github.actor_kpi &&
        echo Kafka topics created successfully.
      '
    networks:
      - ggazers_nw

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    restart: always
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - ggazers_nw

  ggazers-producer:
    build:
      context: ../stream-processing/producer
      dockerfile: Dockerfile
    command: "bash -c 'echo Waiting for Kafka to be ready... && until nc -z schema-registry 8081; do sleep 1; done && python3 src/runner.py'"
    env_file:
      - ../stream-processing/producer/src/.env
    depends_on:
      - broker
      - schema-registry
    networks:
      - ggazers_nw

  ggazers-analyzer:
    build:
      context: ../stream-processing/analyzer
      dockerfile: Dockerfile
    command: "bash -c 'echo Waiting for Kafka to be ready... && until nc -z schema-registry 8081; do sleep 1; done  && java -jar target/scala-2.13/ggazers-0.1.0-SNAPSHOT.jar'"
    depends_on:
      - broker
      - schema-registry
      - ggazers-producer
    networks:
      - ggazers_nw

  ggazers-repokpi-connect:
    build:
      context: ../stream-processing/connect
      dockerfile: Dockerfile
    command: bash -c 'echo Waiting for Kafka to be ready... && until nc -z schema-registry 8081; do sleep 1; done  && python3 runner.py --dataset repo_kpi'
    depends_on:
      - broker
      - schema-registry
      - ggazers-producer
      - ggazers-analyzer
    networks:
      - ggazers_nw
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  ggazers-actorkpi-connect:
    build:
      context: ../stream-processing/connect
      dockerfile: Dockerfile
    command: bash -c 'echo Waiting for Kafka to be ready... && until nc -z schema-registry 8081; do sleep 1; done  && python3 runner.py --dataset actor_kpi'
    depends_on:
      - broker
      - schema-registry
      - ggazers-producer
      - ggazers-analyzer
    networks:
      - ggazers_nw
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

networks:
  ggazers_nw:
    driver: bridge
    name: ggazers_nw